steps:
- name: node
  entrypoint: npm
  dir: 'landing'
  args: ['install']
  id: Install Node Dependencies
# - name: node
#   id: Set Environment
#   entrypoint: npm
#   dir: 'landing'
#   args: ["run", "create-env"]
#   env:
#     - 'REACT_APP_GOOGLE_ANALYTICS_KEY=${_REACT_APP_GOOGLE_ANALYTICS_KEY}'
#     - 'NEXT_PUBLIC_RADIANT_API_URL=${_NEXT_PUBLIC_RADIANT_API_URL}'
#     - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
#     - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
#     - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
#     - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
#     - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
#     - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
#     - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
- name: node
  id: Run Build App
  entrypoint: npm
  dir: 'landing'
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy to App Engine
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  dir: 'landing'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
