steps:
- name: node:16.20.2
  entrypoint: npm
  dir: 'landing'
  args: ['install']
  id: Install Node Dependencies
- name: node:16.20.2
  id: Run Build App
  entrypoint: npm
  dir: 'landing'
  args: ['run', 'build']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy to App Engine
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
  dir: 'landing'
timeout: '1600s'
options:
  logging: CLOUD_LOGGING_ONLY
